#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Accounts.Models.Delivery
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SD_SingleSignOn")]
	public partial class DeliveryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_DESP_Telefono(TB_DESP_Telefono instance);
    partial void UpdateTB_DESP_Telefono(TB_DESP_Telefono instance);
    partial void DeleteTB_DESP_Telefono(TB_DESP_Telefono instance);
    #endregion
		
		public DeliveryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DbmlConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DeliveryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NewAddress> NewAddresses
		{
			get
			{
				return this.GetTable<NewAddress>();
			}
		}
		
		public System.Data.Linq.Table<NewPhone> NewPhones
		{
			get
			{
				return this.GetTable<NewPhone>();
			}
		}
		
		public System.Data.Linq.Table<VW_Address> VW_Addresses
		{
			get
			{
				return this.GetTable<VW_Address>();
			}
		}
		
		public System.Data.Linq.Table<AddressPhone> AddressPhones
		{
			get
			{
				return this.GetTable<AddressPhone>();
			}
		}
		
		public System.Data.Linq.Table<VT_DESP_Direccion> VT_DESP_Direccions
		{
			get
			{
				return this.GetTable<VT_DESP_Direccion>();
			}
		}
		
		public System.Data.Linq.Table<TB_DESP_Telefono> TB_DESP_Telefonos
		{
			get
			{
				return this.GetTable<TB_DESP_Telefono>();
			}
		}
		
		public System.Data.Linq.Table<TB_DESP_DireccionUbicacion> TB_DESP_DireccionUbicacions
		{
			get
			{
				return this.GetTable<TB_DESP_DireccionUbicacion>();
			}
		}
		
		public System.Data.Linq.Table<AddressLocation> AddressLocations
		{
			get
			{
				return this.GetTable<AddressLocation>();
			}
		}
		
		public System.Data.Linq.Table<NewLocation> NewLocations
		{
			get
			{
				return this.GetTable<NewLocation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class NewAddress
	{
		
		private string _address;
		
		private string _number;
		
		private string _department;
		
		private string _type;
		
		private List<NewPhone> _phones;
		
		private List<NewLocation> _locations;
		
		private string _country;
		
		public NewAddress()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Direccion", Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Numero", Storage="_number", DbType="VarChar(10)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_NumeroDepto", Storage="_department", DbType="VarChar(20)")]
		public string houseOrDepto
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this._department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIDI_Nombre", Storage="_type", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phones", CanBeNull=false)]
		public List<NewPhone> phones
		{
			get
			{
				return this._phones;
			}
			set
			{
				if ((this._phones != value))
				{
					this._phones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locations", CanBeNull=false)]
		public List<NewLocation> locations
		{
			get
			{
				return this._locations;
			}
			set
			{
				if ((this._locations != value))
				{
					this._locations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class NewPhone
	{
		
		private string _countryCode;
		
		private int _area;
		
		private string _number;
		
		public NewPhone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_CodigoPais", Storage="_countryCode", CanBeNull=false)]
		public string countryCode
		{
			get
			{
				return this._countryCode;
			}
			set
			{
				if ((this._countryCode != value))
				{
					this._countryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_CodigoArea", Storage="_area")]
		public int areaCode
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_Numero", Storage="_number", CanBeNull=false)]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VT_DESP_Direcciones")]
	public partial class VW_Address
	{
		
		private System.Guid _token;
		
		private string _address;
		
		private string _number;
		
		private string _houseOrDepto;
		
		private System.DateTime _updatedAt;
		
		private string _country;
		
		private string _type_identifier;
		
		private string _type_name;
		
		private List<AddressPhone> _phones;
		
		private List<AddressLocation> _locations;
		
		private string _fullLocation;
		
		public VW_Address()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Token", Storage="_token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid token
		{
			get
			{
				return this._token;
			}
			set
			{
				if ((this._token != value))
				{
					this._token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Direccion", Storage="_address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Numero", Storage="_number", DbType="VarChar(10)")]
		public string number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_NumeroDeptoOCasa", Storage="_houseOrDepto", DbType="VarChar(20)")]
		public string houseOrDepto
		{
			get
			{
				return this._houseOrDepto;
			}
			set
			{
				if ((this._houseOrDepto != value))
				{
					this._houseOrDepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_FechaActualizacion", Storage="_updatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this._updatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DIRE_Pais", Storage="_country", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this._country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIDI_Identificador", Storage="_type_identifier", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string type_identifier
		{
			get
			{
				return this._type_identifier;
			}
			set
			{
				if ((this._type_identifier != value))
				{
					this._type_identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIDI_Nombre", Storage="_type_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string type_name
		{
			get
			{
				return this._type_name;
			}
			set
			{
				if ((this._type_name != value))
				{
					this._type_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phones", CanBeNull=false)]
		public List<AddressPhone> phones
		{
			get
			{
				return this._phones;
			}
			set
			{
				if ((this._phones != value))
				{
					this._phones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_locations", CanBeNull=false)]
		public List<AddressLocation> locations
		{
			get
			{
				return this._locations;
			}
			set
			{
				if ((this._locations != value))
				{
					this._locations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullLocation", CanBeNull=false)]
		public string fullLocation
		{
			get
			{
				return this._fullLocation;
			}
			set
			{
				if ((this._fullLocation != value))
				{
					this._fullLocation = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DESP_Telefono")]
	public partial class AddressPhone
	{
		
		private int _countryCode;
		
		private int _areaCode;
		
		private int _number;
		
		private System.DateTime _updatedAt;
		
		public AddressPhone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_CodigoPais", Storage="_countryCode", DbType="Int NOT NULL")]
		public int countryCode
		{
			get
			{
				return this._countryCode;
			}
			set
			{
				if ((this._countryCode != value))
				{
					this._countryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_CodigoArea", Storage="_areaCode", DbType="Int NOT NULL")]
		public int areaCode
		{
			get
			{
				return this._areaCode;
			}
			set
			{
				if ((this._areaCode != value))
				{
					this._areaCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_Numero", Storage="_number", DbType="Int NOT NULL")]
		public int number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this._number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TELE_FechaActualizacion", Storage="_updatedAt", DbType="DateTime NOT NULL")]
		public System.DateTime updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this._updatedAt = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VT_DESP_Direcciones")]
	public partial class VT_DESP_Direccion
	{
		
		private int _DIRE_Codigo;
		
		private System.Guid _DIRE_Token;
		
		private int _USUA_Codigo;
		
		private string _DIRE_Direccion;
		
		private string _DIRE_Numero;
		
		private string _DIRE_NumeroDeptoOCasa;
		
		private System.DateTime _DIRE_FechaActualizacion;
		
		private string _DIRE_Pais;
		
		private string _TIDI_Identificador;
		
		private string _TIDI_Nombre;
		
		public VT_DESP_Direccion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Codigo", DbType="Int NOT NULL")]
		public int DIRE_Codigo
		{
			get
			{
				return this._DIRE_Codigo;
			}
			set
			{
				if ((this._DIRE_Codigo != value))
				{
					this._DIRE_Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DIRE_Token
		{
			get
			{
				return this._DIRE_Token;
			}
			set
			{
				if ((this._DIRE_Token != value))
				{
					this._DIRE_Token = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUA_Codigo", DbType="Int NOT NULL")]
		public int USUA_Codigo
		{
			get
			{
				return this._USUA_Codigo;
			}
			set
			{
				if ((this._USUA_Codigo != value))
				{
					this._USUA_Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Direccion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DIRE_Direccion
		{
			get
			{
				return this._DIRE_Direccion;
			}
			set
			{
				if ((this._DIRE_Direccion != value))
				{
					this._DIRE_Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Numero", DbType="VarChar(10)")]
		public string DIRE_Numero
		{
			get
			{
				return this._DIRE_Numero;
			}
			set
			{
				if ((this._DIRE_Numero != value))
				{
					this._DIRE_Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_NumeroDeptoOCasa", DbType="VarChar(20)")]
		public string DIRE_NumeroDeptoOCasa
		{
			get
			{
				return this._DIRE_NumeroDeptoOCasa;
			}
			set
			{
				if ((this._DIRE_NumeroDeptoOCasa != value))
				{
					this._DIRE_NumeroDeptoOCasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_FechaActualizacion", DbType="DateTime NOT NULL")]
		public System.DateTime DIRE_FechaActualizacion
		{
			get
			{
				return this._DIRE_FechaActualizacion;
			}
			set
			{
				if ((this._DIRE_FechaActualizacion != value))
				{
					this._DIRE_FechaActualizacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Pais", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string DIRE_Pais
		{
			get
			{
				return this._DIRE_Pais;
			}
			set
			{
				if ((this._DIRE_Pais != value))
				{
					this._DIRE_Pais = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIDI_Identificador", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TIDI_Identificador
		{
			get
			{
				return this._TIDI_Identificador;
			}
			set
			{
				if ((this._TIDI_Identificador != value))
				{
					this._TIDI_Identificador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIDI_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TIDI_Nombre
		{
			get
			{
				return this._TIDI_Nombre;
			}
			set
			{
				if ((this._TIDI_Nombre != value))
				{
					this._TIDI_Nombre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DESP_Telefono")]
	public partial class TB_DESP_Telefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TELE_Codigo;
		
		private int _TELE_CodigoPais;
		
		private int _TELE_CodigoArea;
		
		private int _TELE_Numero;
		
		private System.DateTime _TELE_FechaActualizacion;
		
		private int _DIRE_Codigo;
		
		private System.Guid _DIRE_Token;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTELE_CodigoChanging(int value);
    partial void OnTELE_CodigoChanged();
    partial void OnTELE_CodigoPaisChanging(int value);
    partial void OnTELE_CodigoPaisChanged();
    partial void OnTELE_CodigoAreaChanging(int value);
    partial void OnTELE_CodigoAreaChanged();
    partial void OnTELE_NumeroChanging(int value);
    partial void OnTELE_NumeroChanged();
    partial void OnTELE_FechaActualizacionChanging(System.DateTime value);
    partial void OnTELE_FechaActualizacionChanged();
    partial void OnDIRE_CodigoChanging(int value);
    partial void OnDIRE_CodigoChanged();
    partial void OnDIRE_TokenChanging(System.Guid value);
    partial void OnDIRE_TokenChanged();
    #endregion
		
		public TB_DESP_Telefono()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELE_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TELE_Codigo
		{
			get
			{
				return this._TELE_Codigo;
			}
			set
			{
				if ((this._TELE_Codigo != value))
				{
					this.OnTELE_CodigoChanging(value);
					this.SendPropertyChanging();
					this._TELE_Codigo = value;
					this.SendPropertyChanged("TELE_Codigo");
					this.OnTELE_CodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELE_CodigoPais", DbType="Int NOT NULL")]
		public int TELE_CodigoPais
		{
			get
			{
				return this._TELE_CodigoPais;
			}
			set
			{
				if ((this._TELE_CodigoPais != value))
				{
					this.OnTELE_CodigoPaisChanging(value);
					this.SendPropertyChanging();
					this._TELE_CodigoPais = value;
					this.SendPropertyChanged("TELE_CodigoPais");
					this.OnTELE_CodigoPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELE_CodigoArea", DbType="Int NOT NULL")]
		public int TELE_CodigoArea
		{
			get
			{
				return this._TELE_CodigoArea;
			}
			set
			{
				if ((this._TELE_CodigoArea != value))
				{
					this.OnTELE_CodigoAreaChanging(value);
					this.SendPropertyChanging();
					this._TELE_CodigoArea = value;
					this.SendPropertyChanged("TELE_CodigoArea");
					this.OnTELE_CodigoAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELE_Numero", DbType="Int NOT NULL")]
		public int TELE_Numero
		{
			get
			{
				return this._TELE_Numero;
			}
			set
			{
				if ((this._TELE_Numero != value))
				{
					this.OnTELE_NumeroChanging(value);
					this.SendPropertyChanging();
					this._TELE_Numero = value;
					this.SendPropertyChanged("TELE_Numero");
					this.OnTELE_NumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELE_FechaActualizacion", DbType="DateTime NOT NULL")]
		public System.DateTime TELE_FechaActualizacion
		{
			get
			{
				return this._TELE_FechaActualizacion;
			}
			set
			{
				if ((this._TELE_FechaActualizacion != value))
				{
					this.OnTELE_FechaActualizacionChanging(value);
					this.SendPropertyChanging();
					this._TELE_FechaActualizacion = value;
					this.SendPropertyChanged("TELE_FechaActualizacion");
					this.OnTELE_FechaActualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Codigo", DbType="Int NOT NULL")]
		public int DIRE_Codigo
		{
			get
			{
				return this._DIRE_Codigo;
			}
			set
			{
				if ((this._DIRE_Codigo != value))
				{
					this.OnDIRE_CodigoChanging(value);
					this.SendPropertyChanging();
					this._DIRE_Codigo = value;
					this.SendPropertyChanged("DIRE_Codigo");
					this.OnDIRE_CodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Token", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid DIRE_Token
		{
			get
			{
				return this._DIRE_Token;
			}
			set
			{
				if ((this._DIRE_Token != value))
				{
					this.OnDIRE_TokenChanging(value);
					this.SendPropertyChanging();
					this._DIRE_Token = value;
					this.SendPropertyChanged("DIRE_Token");
					this.OnDIRE_TokenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DESP_DireccionUbicacion")]
	public partial class TB_DESP_DireccionUbicacion
	{
		
		private int _DIRE_Codigo;
		
		private int _UBIC_Codigo;
		
		private int _UBIC_TIUB_Codigo;
		
		private string _UBIC_Nombre;
		
		public TB_DESP_DireccionUbicacion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRE_Codigo", DbType="Int NOT NULL")]
		public int DIRE_Codigo
		{
			get
			{
				return this._DIRE_Codigo;
			}
			set
			{
				if ((this._DIRE_Codigo != value))
				{
					this._DIRE_Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBIC_Codigo", DbType="Int NOT NULL")]
		public int UBIC_Codigo
		{
			get
			{
				return this._UBIC_Codigo;
			}
			set
			{
				if ((this._UBIC_Codigo != value))
				{
					this._UBIC_Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBIC_TIUB_Codigo")]
		public int UBIC_TIUB_Codigo
		{
			get
			{
				return this._UBIC_TIUB_Codigo;
			}
			set
			{
				if ((this._UBIC_TIUB_Codigo != value))
				{
					this._UBIC_TIUB_Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UBIC_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string UBIC_Nombre
		{
			get
			{
				return this._UBIC_Nombre;
			}
			set
			{
				if ((this._UBIC_Nombre != value))
				{
					this._UBIC_Nombre = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_DESP_DireccionUbicacion")]
	public partial class AddressLocation
	{
		
		private int _id;
		
		private int _type;
		
		private string _name;
		
		public AddressLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_Codigo", Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_TIUB_Codigo", Storage="_type")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_Nombre", Storage="_name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class NewLocation
	{
		
		private int _id;
		
		private string _name;
		
		private int _type;
		
		private System.Nullable<int> _parent;
		
		public NewLocation()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_Codigo", Storage="_id")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_Nombre", Storage="_name", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="TIUB_Codigo", Storage="_type")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="UBIC_Codigo_Padre", Storage="_parent")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this._parent = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
