<?xml version="1.0" encoding="utf-8"?><Database Name="SD_SingleSignOn" Class="AccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=SD_SingleSignOn;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DbmlConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TB_AUT_Usuario" Member="NewAccounts">
    <Type Name="NewAccount">
      <Column Name="USUA_Email" Member="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USUA_NombreCompleto" Member="fullname" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="APER_Contrasena" Member="password" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="avatar" Type="System.Guid" CanBeNull="true" />
      <Column Member="nationalId" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>