//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Endpoints.Oauth2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OAuth2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OAuth2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Endpoints.Oauth2.Resources.OAuth2", typeof(OAuth2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client_id for the application is invalid or dont exist&apos;s.
        /// </summary>
        internal static string APPLICATION_INVALID {
            get {
                return ResourceManager.GetString("APPLICATION_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        internal static string CLIENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("CLIENT_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tu información de despacho.
        /// </summary>
        internal static string delivery {
            get {
                return ResourceManager.GetString("delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameters body is empty.
        /// </summary>
        internal static string PARAMETERS_REQUIRED {
            get {
                return ResourceManager.GetString("PARAMETERS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required to authenticate.
        /// </summary>
        internal static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tus datos de pago.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tu información basica.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        internal static string PROMPT_REQUIRED {
            get {
                return ResourceManager.GetString("PROMPT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        internal static string REDIRECT_URI_REQUIRED {
            get {
                return ResourceManager.GetString("REDIRECT_URI_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        internal static string RESPONSE_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("RESPONSE_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope requested for the application is not valid or not authorized.
        /// </summary>
        internal static string SCOPE_REQUESTED_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("SCOPE_REQUESTED_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is required.
        /// </summary>
        internal static string SCOPE_REQUIRED {
            get {
                return ResourceManager.GetString("SCOPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario o la contraseña que ingresaste es incorrecta..
        /// </summary>
        internal static string USERNAME_OR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("USERNAME_OR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is required to authenticate.
        /// </summary>
        internal static string USERNAME_REQUIRED {
            get {
                return ResourceManager.GetString("USERNAME_REQUIRED", resourceCulture);
            }
        }
    }
}
